[book]
authors = ["Nutpapop Yasawut"]
language = "en"
multilingual = false
src = "src"
title = "Fallout Wiki"

[build]
build-dir = "..\\..\\public\\fallout\\wiki"
use-default-preprocessors = false

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["custom.css"]
site-url = "/fallout/wiki/"

[output.html.search]
limit-results = 15